# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160526_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='chapin',
            field=models.TextField(default='0', verbose_name='差评'),
        ),
        migrations.AddField(
            model_name='blog',
            name='dianzan',
            field=models.TextField(default='0', verbose_name='点赞'),
        ),
        migrations.AddField(
            model_name='blog',
            name='look',
            field=models.TextField(default='0', verbose_name='浏览量'),
        ),
    ]
