# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160529_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='look',
            field=models.PositiveIntegerField(default=4, verbose_name='浏览量'),
        ),
    ]
