# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160606_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
