# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160606_1937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
