# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_myuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='type',
            new_name='types',
        ),
    ]
