# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160606_2000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default=14, max_length=16, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
